package A2;
import java.util.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
/**
 * main JFrame display for Assignment2
 * 
 * @author mdyuong
 */

public class AdminBoard extends javax.swing.JFrame {
    /**
     * for the purpose of the singleton design pattern
     */
    private static AdminBoard instance = null;
    /**
     * data structure to keep track of all Person objects
     */
    private   Set<Person> everyone = new HashSet();
    /**
     * data structure to keep track of all groups
     */
    private   Set<Group> group1 = new HashSet();
    /**
     * purpose: to create the visitor design pattern
     */
    private ButtonPeople bp;
     /**
     * purpose: to create the visitor design pattern
     */
    private ButtonGroup bg;
     /**
     * purpose: to create the visitor design pattern
     */
    private ButtonTotalMessages tm;
     /**
     * purpose: to create the visitor design pattern
     */
    private ButtonPositiveMessages pm;
    /**
     * purpose: to recreate the JTree in the JFrame when a new Person or Group is added
     */
    private  DefaultTreeModel model;
    /**
     * Creates new form AdminBoard and initializes the objects within the frame
     */
    private AdminBoard() 
    {
        initComponents();
        model = (DefaultTreeModel)jTree1.getModel();
        bp = new ButtonPeople(userTotal, everyone);
        bg = new ButtonGroup(groupTotal, group1);
        tm = new ButtonTotalMessages(messageTotal, everyone);
        pm = new ButtonPositiveMessages(positivePercent, everyone);
        
    }
    /**
     * purpose: singleton design pattern, make sure only one instance of AdminBoard is created
     * @return 
     */
    public static AdminBoard getInstance()
    {
        if(instance == null)
        {
            instance = new AdminBoard();
        }
      return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        user = new javax.swing.JTextField();
        group = new javax.swing.JTextField();
        addUser = new javax.swing.JButton();
        addGroup = new javax.swing.JButton();
        openUserView = new javax.swing.JButton();
        userTotal = new javax.swing.JButton();
        groupTotal = new javax.swing.JButton();
        messageTotal = new javax.swing.JButton();
        positivePercent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupActionPerformed(evt);
            }
        });

        addUser.setText("Add User");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        addGroup.setText("Add Group");
        addGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupActionPerformed(evt);
            }
        });

        openUserView.setText("Open User View");
        openUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openUserViewActionPerformed(evt);
            }
        });

        userTotal.setText("User Total");
        userTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTotalActionPerformed(evt);
            }
        });

        groupTotal.setText("Group Total");
        groupTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupTotalActionPerformed(evt);
            }
        });

        messageTotal.setText("Message Total");
        messageTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTotalActionPerformed(evt);
            }
        });

        positivePercent.setText("Positive Percent");
        positivePercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positivePercentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(openUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(user)
                                    .addComponent(group, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(userTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(messageTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(groupTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(positivePercent, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(group)
                            .addComponent(addGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(openUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(messageTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(positivePercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupActionPerformed
    /**
     * action performed when the "user total" button is clicked
     * opens another JFrame where the total number of people is displayed
     * @param evt 
     */
    private void userTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTotalActionPerformed
       Visit cv = new CountVisit();
        bp.accept(cv);
        
        
    }//GEN-LAST:event_userTotalActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed
    /**
     * purpose: to help add a Person object into the JTree at specified location
     */
    DefaultMutableTreeNode selected;
     /**
     * action performed when the "add user" button is clicked
     * Person with specified name is added to the tree
     * @param evt 
     */
    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        selected = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
        if(selected != null)
        {
          if( !user.getText().equals(""))
            { 
                 Person p = new Person(user.getText());
                 selected.insert(new DefaultMutableTreeNode(user.getText(),false),0 );
                 model.reload(selected);
                 everyone.add(p);
                 for(Group g: group1)
                 {
                     if(g.getName().equals(selected.toString()))
                     {
                         g.addToGroup(p);
                     }
                 }
            }
            else
            {
                Display dis = new Display("No identifier was entered.");
                dis.setVisible(true);
            }
        }
        user.setText("");
    }//GEN-LAST:event_addUserActionPerformed
     /**
      * purpose: to help add a Group object to the JTree
      * group with specified name is added to the tree
      */
      DefaultMutableTreeNode selected2;
     /**
     * action performed when the "add group" button is clicked
     * specified group is added to JTree
     * @param evt 
     */
    private void addGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupActionPerformed
        selected2 = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
        if(selected2 != null)
        {
            if( !group.getText().equals(""))
            {
              selected2.insert(new DefaultMutableTreeNode(group.getText(),true),0 );
              model.reload(selected2);
              group1.add(new Group(group.getText()));
            }
            else
            {
                Display dis = new Display("No identifier was entered.");
                dis.setVisible(true);
            }
        }
        group.setText("");
    }//GEN-LAST:event_addGroupActionPerformed
    //DefaultMutableTreeNode selected3;
    /**
     * action performed when the "open user view" button is clicked 
     * opens the specified user's frame
     * @param evt 
     */
    private void openUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openUserViewActionPerformed
       selected = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
       if(selected != null)
       {
          UserBoard ub = new UserBoard(selected.toString(), everyone);
          for(Person p: everyone)
          {
              if(p.getName().equals(selected.toString()))
              {
                p.associateUBwithPerson(ub);
                p.setUBVisible();
              }
          }
          
       }
    }//GEN-LAST:event_openUserViewActionPerformed
    /**
     * action performed when the "group total" button is clicked
     * opens another JFrame where the total number of groups is displayed
     * @param evt 
     */
    private void groupTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupTotalActionPerformed
        Visit gcv = new CountVisit();
        bg.accept(gcv);
        
    }//GEN-LAST:event_groupTotalActionPerformed
    /**
     * action performed when the "message total" button is clicked
     * opens another JFrame where the total number of messages is displayed
     * @param evt 
     */
    private void messageTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTotalActionPerformed
        Visit mtv = new CountVisit();
        tm.accept(mtv);
    }//GEN-LAST:event_messageTotalActionPerformed
   /**
     * action performed when the "positive message total" button is clicked
     * opens another JFrame where the total number of positive messages is displayed
     * @param evt 
     */
    private void positivePercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positivePercentActionPerformed
        Visit tmv = new CountVisit();
        pm.accept(tmv);
        
    }//GEN-LAST:event_positivePercentActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroup;
    private javax.swing.JButton addUser;
    private javax.swing.JTextField group;
    private javax.swing.JButton groupTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton messageTotal;
    private javax.swing.JButton openUserView;
    private javax.swing.JButton positivePercent;
    private javax.swing.JTextField user;
    private javax.swing.JButton userTotal;
    // End of variables declaration//GEN-END:variables
}
